### ISSUE TITLE
Signup workflow

### ISSUE THREAD

**Issue by mz106** [mz106/climbing-buddy-fe#10]
A design of the workflow for the UX on signup

**Comment by mz106** [comment]
Cannot use localstorage, it creates a security issue. Besides, the data is not yet designed so any copy and pasting of code would render the app ineffective. Once I have designed the requests I shall let you know. 

And this issue is for a UX design, and not code.

**Comment by bar-alex** [comment]
Oh, I just saw this message, I guess my post on the login issue is useless. 

I propose to only hold data in localStorage (because of convenience) that doesn't matter security-wise, the token is encrypted, you can't get the info out of it and it can't be copied and used on a different system - and this is only to have the auto-login feature, if we don't need that then we don't need to store the token anywhere that survives between sessions. 

Then again, you mentioned you want to use a passport so I'll leave that up to you as I know nothing about it. 

I didn't mean to just copy and paste code from there, I mean to use it as inspiration, because I imagine we'll need something similar here. 

Look, I don't know how to do these and it looks like I'm doing it wrong, so I'll refrain from adding anything until you clarify, which will probably happen tomorrow :)

**Comment by bar-alex** [comment]
The workflow diagram was done and merged with the documentation branch.
